/etc/passwd     NORMAL
/etc/shadow     NORMAL
/etc/group      NORMAL
/etc/sudoers    NORMAL
/etc/ssh        NORMAL

/bin            NORMAL
/sbin           NORMAL
/usr/bin        NORMAL
/usr/sbin       NORMAL
/boot           NORMAL

!/var/log/.*
!/var/tmp/.*
!/tmp/.*
!/run/.*
!/var/lib/apt/.*
!/var/cache/.*
!/var/lib/systemd/.*
!/var/spool/.*
!/home/*/.cache/.*

!/etc/mtab
!/etc/hostname
!/etc/hosts
!/etc/resolv.conf
!/etc/machine-id
