apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.__BASE_DOMAIN__
  issuerRef:
    name: __CLUSTER_ISSUER__
    kind: ClusterIssuer
